name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Multi-objective test suite
      id: multi-objective-test-suite
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 5
        max-score: 10
        setup-command: sudo -H pip3 install -r requirements.txt
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MULTI-OBJECTIVE-TEST-SUITE_RESULTS: "${{steps.multi-objective-test-suite.outputs.result}}"
      with:
        runners: multi-objective-test-suite
